export const itrColors = {
  headerGradientStart: "#3A7BFF",
  headerGradientEnd: "#35CDBB",
  headerText: "#FFFFFF",
  headerBadgeBg: "#F7C84A",
  headerBadgeText: "#0F172A",
  background: "#F4F8FF",
  surface: "#FFFFFF",
  card: "#FFFFFF",
  text: "#0F172A",
  textSecondary: "#5B6B84",
  textMuted: "#7B879A",
  border: "#E4ECF8",
  borderSoft: "#EEF3FB",
  primary: "#3A7BFF",
  primarySoft: "#EAF1FF",
  success: "#16A34A",
  warning: "#D97706",
  danger: "#DC2626",
  emptyIcon: "#D1D9E8",
} as const;
